---
- name: add egress to existing splunk instance
  hosts: '{{ splunk_group }}'
  gather_facts: no

  vars:
    region: ap-southeast-2
    egress_sg: sg-abc
    group_ids: ['{{ egress_sg }}']

  tasks:
    - ec2_metadata_facts:

    - ec2_instance_facts:
        region: '{{ region }}'
        instance_ids:
          - "{{ ansible_ec2_instance_identity_document_instanceid }}"
      register: ec2_info

    # - debug: var=ec2_info
    - set_fact:
        group_ids_current: "{{ ec2_info.instances.0.security_groups | map(attribute='group_id') | list }} "

    - set_fact:
        group_ids: "{{ group_ids_current | union(group_ids) }}"

#    - set_fact:
#        group_ids: ec2_info.instances.0.security_groups
      #  group_ids: "{{ ec2_info.instances.0.security_groups }} | union({{ group_ids }})"
#        group_ids: "{{ group_ids }} + ['{{ item.group_id }}']"
#      with_items: '{{ ec2_info.instances.0.security_groups }}'

    - debug: var=group_ids
