- name: ping host
  hosts: localhost
  gather_facts: no
  tasks:
    - name: getting remote script output
      shell: env -abc
      register: env_response
      ignore_errors: yes


    - debug:
         msg: "{{ env_response }}"
